### ISSUE TITLE
Blank Screen on Load - Side Bar is Visible

### ISSUE THREAD

**Issue by rapterjet2004** [nextcloud/ocs_api_viewer#17]
### Screenshot
<img width="626" alt="image" src="https://github.com/nextcloud/ocs_api_viewer/assets/69230048/50bc429f-24c2-47b1-a4da-2688a8921721">

### DevTools returns a couple errors

Upon loading the OCS API Viewer
```
Uncaught Error: Could not find initial state limit-default of unified-search
    at r (toast-d1cd63b1.mjs:26:84447)
    at 93410 (Filter.vue:1:71)
    at o (SearchFilterChip.vue:6:954)
    at SearchResult.vue:6:1723
    at o.O (SearchFilterChip.vue:6:954)
    at SearchResult.vue:6:1723
    at SearchResult.vue:6:1723
```

Upon navigating to `spreed`

>Refused to load the script 'http://localhost:8080/apps-writable/ocs_api_viewer/js/stoplight-elements.js' because it violates the following Content Security Policy directive: "script-src-elem 'strict-dynamic' 'nonce-czZ0YWRjQjRyRTd0ZmZad2EreUI2ODI3cXhON3JVcEtqNytUZmRZVFp0az06eDU0S0lLZEI5ajZaUktCSlBMLzNnYnZDbkh3NitCd0IxZFBpQ3I1S0lJcz0=' blob: 'unsafe-eval' 'unsafe-inline' *". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'http:' must be added explicitly.

>Refused to load the script 'http://localhost:8080/apps-writable/ocs_api_viewer/js/ocs_api_viewer-iframe-theme.js' because it violates the following Content Security Policy directive: "script-src-elem 'strict-dynamic' 'nonce-czZ0YWRjQjRyRTd0ZmZad2EreUI2ODI3cXhON3JVcEtqNytUZmRZVFp0az06eDU0S0lLZEI5ajZaUktCSlBMLzNnYnZDbkh3NitCd0IxZFBpQ3I1S0lJcz0=' blob: 'unsafe-eval' 'unsafe-inline' *". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'http:' must be added explicitly.

### Versions
- server: 29.0.0 dev
- ocs_api_viewer: 1.0.4

**Comment by provokateurin** [comment]
The first error is not related to this app. The CSP problems were fixed in https://github.com/nextcloud/ocs_api_viewer/pull/15, but I haven't done a release yet. Just use the latest git version to get it working on server 28+

**Comment by rapterjet2004** [comment]
Got it, just cloned the main branch
`git clone https://github.com/nextcloud/ocs_api_viewer.git -b main`

unfortunately now the entire screen is empty. Is this expected? Checked and `oc_security_csp_contentsecuritypolicynoncemanager.php` was there

<img width="957" alt="image" src="https://github.com/nextcloud/ocs_api_viewer/assets/69230048/460a51f1-7c0e-4326-b35f-a3b9a1a12467">

**Comment by nickvergessen** [comment]
And `composer i --no-dev`
