### ISSUE TITLE
Can not send empty string on required string fields

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/ocs_api_viewer#18]
Was unable to test e.g. https://github.com/nextcloud/spreed/pull/11207#issuecomment-1885803158

**Comment by provokateurin** [comment]
Upstream problem in https://github.com/stoplightio/elements. I guess when a parameter is required it only checks the that there is a value (e.g. by length), but for a string an empty string is also a valid value.

**Comment by provokateurin** [comment]
Same for empty arrays

**Comment by provokateurin** [comment]
Should be fixed by https://github.com/nextcloud/openapi-extractor/pull/105
