### ISSUE TITLE
List of children not shown

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/ocs_api_viewer#20]
Problematic controller:
https://github.com/nextcloud/spreed/blob/4c5128dc22af05217df9e9d044515dbf921e05dc/lib/Controller/ReactionController.php#L63

```php
*@return DataResponse<Http::STATUS_OK|Http::STATUS_CREATED, array<string, TalkReaction[]>
```

Resulting data:
https://github.com/nextcloud/spreed/blob/bac9eb8652e009c8e13b52d0c6815bc0432740e0/openapi.json#L8496-L8504
```json
                                            "properties": {
                                                "meta": {
                                                    "$ref": "#/components/schemas/OCSMeta"
                                                },
                                                "data": {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "type": "array",
                                                        "items": {
                                                            "$ref": "#/components/schemas/Reaction"
                                                        }
                                                    }
                                                }
                                            }
```

The sample shows the details, but the schema is not visible in the main area:
![grafik](https://github.com/nextcloud/ocs_api_viewer/assets/213943/4940a655-ad7d-4977-81ff-a77c7b2ae60d)

Mostlikely an upstream bug again?

**Comment by nickvergessen** [comment]
Any clever idea for a workaround how I could name sample "emojis" here or even add documentation about what the key of the array is?

**Comment by nickvergessen** [comment]
That works for me

**Comment by provokateurin** [comment]
But it needs to be implemented first

**Comment by provokateurin** [comment]
![image](https://github.com/nextcloud/ocs_api_viewer/assets/26026535/f0e80998-a986-41d5-a792-ae40158cbdad)
In the latest version this is displayed correctly, can we close this?
