### ISSUE TITLE
Request sample/response sample hard to read in dark mode

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/ocs_api_viewer#33]
Light mode:
<img width="469" alt="image" src="https://github.com/user-attachments/assets/02dedbee-5e8d-409d-ba72-a52b4acf85fe">

Dark mode:
<img width="470" alt="image" src="https://github.com/user-attachments/assets/714bb039-9881-4b28-bdfa-2f51e7bb71b5">

Could we adjust the theming here a bit?

**Comment by provokateurin** [comment]
I noticed this as well, but unfortunately this is an upstream issue in the library: https://github.com/stoplightio/elements/issues/2188.
I tried the workaround described in https://github.com/stoplightio/elements/issues/2188#issuecomment-1485461965, but that doesn't seem to work anymore.
There is nothing really we can do here it seems, so I'll close this for now.
