### ISSUE TITLE
Update URL when opening elements

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/ocs_api_viewer#34]
Currently when I navigate to `spreed -> room -> something` the URL of the browser stays at `https://host/apps/ocs_api_viewer/#`, while the link of the element itself is `https://host/apps/ocs_api_viewer/view/spreed#/operations/room-set-mention-permissions`. Would it be possible to also change the URL when we navigate inside the ocs_api_viewer app? It would make reloading and copying links to particular APIs easier.

**Comment by provokateurin** [comment]
I'm not sure, the whole thing runs inside an iframe because of interfering styles. I guess it would be possible to communicate between the iframe and the main page using postMessage.
